name:                odd-jobs
version:             0.2.2
synopsis: A full-featured PostgreSQL-backed job queue (with an admin UI)
description: |
  - Background jobs library for Haskell.
  - Extracted from production code at [Vacation Labs](https://www.vacationlabs.com).
  - Inspired by the Delayed Jobs library in Rails.
  - Queue backend is a Postgres table.
  - Queue is monitored using, both, LISTEN/NOTIFY and polling the DB.
  - Comes with an in-built admin UI.
  - Comes with utilities to help you built a CLI for your job-queue.
  - Highly configurable and monitorable
homepage:            https://www.haskelltutorials.com/odd-jobs
bug-reports:         https://github.com/saurabhnanda/odd-jobs/issues
license:             BSD3
author:              Saurabh Nanda
maintainer:          saurabhnanda@gmail.com
copyright:           2016-2020 Saurabh Nanda
category:            Web
extra-source-files:
- README.md
- CHANGELOG.md
- assets/bootstrap/css/bootstrap-grid.css
- assets/bootstrap/css/bootstrap-grid.min.css
- assets/bootstrap/css/bootstrap-reboot.css
- assets/bootstrap/css/bootstrap-reboot.min.css
- assets/bootstrap/css/bootstrap.css
- assets/bootstrap/css/bootstrap.min.css
- assets/bootstrap/js/bootstrap.bundle.js
- assets/bootstrap/js/bootstrap.bundle.min.js
- assets/bootstrap/js/bootstrap.js
- assets/bootstrap/js/bootstrap.min.js
- assets/css/Navigation-Clean1.css
- assets/css/logo-slider.css
- assets/css/styles.css
- assets/js/custom.js
- assets/js/jquery.min.js
- assets/js/logo-slider.js
- assets/odd-jobs-color-logo.png


ghc-options:
  - -Wall
  - -fno-warn-orphans
  - -fno-warn-unused-imports
  - -fno-warn-dodgy-exports
  - -Werror=missing-fields
  - -Werror=incomplete-patterns

default-extensions:
  - NamedFieldPuns
  - LambdaCase
  - TemplateHaskell
  - ScopedTypeVariables
  - GeneralizedNewtypeDeriving
  - QuasiQuotes
  - OverloadedStrings

dependencies:
  - base >= 4.7 && < 5
  - text
  - postgresql-simple
  - bytestring
  - safe
  - text-conversions
  - aeson
  - resource-pool
  - unliftio
  - unliftio-core
  - mtl
  - monad-logger
  - fast-logger
  - either
  - time
  - unix
  - monad-control
  - string-conv
  - hostname
  - lucid
  - timing-convenience
  - friendly-time
  - servant
  - servant-server
  - servant-lucid
  - warp
  - unordered-containers
  - optparse-applicative
  - direct-daemonize
  - filepath
  - directory
  - generic-deriving
  - servant-static-th
  - wai

library:
  source-dirs:
    - src
  exposed-modules:
    - OddJobs.Job
    - OddJobs.Migrations
    - OddJobs.Web
    - OddJobs.Endpoints
    - OddJobs.Cli
    - OddJobs.Types
    - OddJobs.ConfigBuilder

executables:
  devel:
    source-dirs:
      - dev
      - src
    main:             DevelMain
    ghc-options:
      - -threaded
      - -with-rtsopts=-N
    dependencies:
      - foreign-store
      - odd-jobs

  odd-jobs-cli-example:
    main: OddJobsCliExample.lhs
    source-dirs:
      - examples
    ghc-options:
      - -threaded
      - -with-rtsopts=-N
      - -main-is OddJobsCliExample
    dependencies:
      - odd-jobs

tests:
  jobrunner:
    ghc-options:
      - -threaded
      - -with-rtsopts=-N
    main: Test
    source-dirs:
      - test
      - src
    dependencies:
      - tasty
      - tasty-discover
      - hedgehog
      - tasty-hedgehog
      - tasty-hunit
      - random
      - monad-control
      - mmorph
      - lifted-base
      - lifted-async
      - containers
      - tmp-postgres
